### ISSUE TITLE
Webpack issue

### ISSUE THREAD

**Issue by polc** [BigstickCarpet/swagger-parser#48]
Hello,

I'm using swagger-parser@beta. When I try to use SwaggerParser in my React application I got this error : 
```
ERROR in ./~/swagger-schema-official/schema.json
Module parse failed: /home/***/node_modules/swagger-schema-official/schema.json Unexpected token (2:9)
You may need an appropriate loader to handle this file type.
    SyntaxError: Unexpected token (2:9)
at Parser.pp$4.raise (/home/***/node_modules/acorn/dist/acorn.js:2221:15)
at Parser.pp.unexpected (/home/***/node_modules/acorn/dist/acorn.js:603:10)
at Parser.pp.semicolon (/home/***/node_modules/acorn/dist/acorn.js:581:61)
at Parser.pp$1.parseExpressionStatement (/home/***/node_modules/acorn/dist/acorn.js:966:10)
at Parser.pp$1.parseStatement (/home/***/node_modules/acorn/dist/acorn.js:730:24)
at Parser.pp$1.parseBlock (/home/***/node_modules/acorn/dist/acorn.js:981:25)
at Parser.pp$1.parseStatement (/home/***/node_modules/acorn/dist/acorn.js:709:33)
at Parser.pp$1.parseTopLevel (/home/***/node_modules/acorn/dist/acorn.js:638:25)
at Parser.parse (/home/***/node_modules/acorn/dist/acorn.js:516:17)
at Object.parse (/home/***/node_modules/acorn/dist/acorn.js:3098:39)
@ ./~/swagger-parser/lib/validate-schema.js 6:20-61

ERROR in ./~/json-schema-ref-parser/lib/resolvers/file.js
Module not found: Error: Cannot resolve module 'fs' in /home/***/node_modules/json-schema-ref-parser/lib/resolvers
@ ./~/json-schema-ref-parser/lib/resolvers/file.js 2:14-27

ERROR in ./~/z-schema/src/schemas/schema.json
Module parse failed: /home/***/node_modules/z-schema/src/schemas/schema.json Unexpected token (2:8)
You may need an appropriate loader to handle this file type.
    SyntaxError: Unexpected token (2:8)
at Parser.pp$4.raise (/home/***/node_modules/acorn/dist/acorn.js:2221:15)
at Parser.pp.unexpected (/home/***/node_modules/acorn/dist/acorn.js:603:10)
at Parser.pp.semicolon (/home/***/node_modules/acorn/dist/acorn.js:581:61)
at Parser.pp$1.parseExpressionStatement (/home/***/node_modules/acorn/dist/acorn.js:966:10)
at Parser.pp$1.parseStatement (/home/***/node_modules/acorn/dist/acorn.js:730:24)
at Parser.pp$1.parseBlock (/home/***/node_modules/acorn/dist/acorn.js:981:25)
at Parser.pp$1.parseStatement (/home/***/node_modules/acorn/dist/acorn.js:709:33)
at Parser.pp$1.parseTopLevel (/home/***/node_modules/acorn/dist/acorn.js:638:25)
at Parser.parse (/home/***/node_modules/acorn/dist/acorn.js:516:17)
at Object.parse (/home/***/node_modules/acorn/dist/acorn.js:3098:39)
@ ./~/z-schema/src/ZSchema.js 12:24-56

ERROR in ./~/z-schema/src/schemas/hyper-schema.json
Module parse failed: /home/***/node_modules/z-schema/src/schemas/hyper-schema.json Unexpected token (2:13)
You may need an appropriate loader to handle this file type.
    SyntaxError: Unexpected token (2:13)
at Parser.pp$4.raise (/home/***/node_modules/acorn/dist/acorn.js:2221:15)
at Parser.pp.unexpected (/home/***/node_modules/acorn/dist/acorn.js:603:10)
at Parser.pp.semicolon (/home/***/node_modules/acorn/dist/acorn.js:581:61)
at Parser.pp$1.parseExpressionStatement (/home/***/node_modules/acorn/dist/acorn.js:966:10)
at Parser.pp$1.parseStatement (/home/***/node_modules/acorn/dist/acorn.js:730:24)
at Parser.pp$1.parseBlock (/home/***/node_modules/acorn/dist/acorn.js:981:25)
at Parser.pp$1.parseStatement (/home/***/node_modules/acorn/dist/acorn.js:709:33)
at Parser.pp$1.parseTopLevel (/home/***/node_modules/acorn/dist/acorn.js:638:25)
at Parser.parse (/home/***/node_modules/acorn/dist/acorn.js:516:17)
at Object.parse (/home/***/node_modules/acorn/dist/acorn.js:3098:39)
@ ./~/z-schema/src/ZSchema.js 13:24-62
```

**Comment by BigstickCarpet** [comment]
It looks like you're loading the Node.js version, rather than the browser version.  Point your webpack config to `dist/swagger-parser.js` or `dist/swagger-parser.min.js` instead of `lib/index.js`

**Comment by polc** [comment]
oh yeah right, thanks you !
